- src/Plate/index.tsx
- src/Plate/plate.test.tsx
> feat: Add flow-direction to Plate component and export coordinate functions

- src/Modal/FullScreenModal.tsx
- src/Modal/WithModal.tsx
- src/Modal/index.stories.tsx
- src/Modal/index.tsx
Supposed to replace our `ButtonWithModal` and `IconWithModal` components
> feat: add WithModal component

- src/Button/index.stories.tsx
- src/Modal/WithModal.tsx
- src/Modal/index.stories.tsx
BREAKING CHANGE: remove props Component and componentProps from WithModal component
> feat: use render prop opener for WithModal component

- src/Form/index.tsx
Export FormItemProps type.
Resolves: https://github.com/mll-lab/react-components/issues/78
> refactor: export FormItemProps type

- src/Checkbox/index.stories.tsx
- src/Checkbox/index.tsx
- src/antd.less
Improves readability of (all) disabled elements.
Default look:
Disabled look:
Before: 
This fit better into our current styleguide.
> Feat improve disabled readability

- src/Plate/index.stories.tsx
- src/Plate/index.tsx
- src/Plate/plate.test.tsx
feat: change selected property of well to color
BREAKING CHANGE: use color attribute for well instead of deprecated selected
> feat: make plate data nullable

- src/Spinner/MllSpinnerIcon.tsx
https://github.com/styled-components/babel-plugin-styled-components/issues/216#issuecomment-516941240
> fix: workaround styled-components + jest issue

- src/Plate/index.stories.tsx
> fix: display plate component in storybook

- src/Plate/index.stories.tsx
- src/Plate/index.tsx
Resolves https://github.com/mll-lab/react-components/issues/138
> fix: set flex only on default content of a plate well but not on content set by an user

- src/Spinner/index.tsx
fix: shrink style scope
Otherwise the style will be inherited by the children also.
> Shrink style scope

- src/Button/index.tsx
So it is possible to properly type refs outside of the library.
> feat: export ButtonRef type

- src/BackTop/index.stories.tsx
- src/BackTop/index.tsx
Add the BackTop component from https://ant.design/components/back-top/
> feat: Add BackTop component

- src/Checkbox/index.stories.tsx
- src/Checkbox/index.tsx
- src/Provider/index.stories.tsx
> feat: align checkbox with form label

- src/Tabs/TabPanel.tsx
- src/Tabs/Tabs.tsx
- src/Tabs/TabsContext.tsx
- src/Tabs/TabsHeader.tsx
- src/Tabs/index.stories.tsx
- src/Tabs/index.test.tsx
- src/Tabs/types.ts
BREAKING CHANGE: rename Id to ID in Tabs
> feat: add generic type TTabID to tabs

- src/Button/ColoredButtons.tsx
Resolves https://github.com/mll-lab/react-components/issues/195
> feat: improve Button contrast on dark backgrounds

- src/Input/index.stories.tsx
- src/Skeleton/index.tsx
- src/Space/index.tsx
- yarn.lock
Repeats the overeagerly merged https://github.com/mll-lab/react-components/pull/200, fixing the pipeline errors.
> chore: update antd dependency

- package.json
- src/MasterMix/MasterMix.test.tsx
- src/MasterMix/index.stories.tsx
- src/MasterMix/index.tsx
- src/MasterMix/pipettingLossTableColumn.test.tsx
- src/MasterMix/pipettingLossTableColumn.tsx
- src/MasterMix/types.ts
- yarn.lock
BREAKING CHANGE: MasterMix-Component requires pipettingLoss-property
> feat: Add dynamic pipetting loss to MasterMix

- src/Input/common.ts
- src/Input/index.stories.tsx
> feat: add SearchProps

- src/Select/formInput.ts
- src/Select/index.tsx
- src/Table/index.tsx
- src/Table/utils.test.ts
- src/Table/utils.ts
BREAKING CHANGE: rename labeledEnumToColumnFilterItem to objectToColumnFilterItem
> feat: introduce *ToColumnFilterItem utils

- src/Table/index.stories.tsx
- src/Table/index.tsx
- src/theme.ts
ColoredTable is added to the library.
> Add colored table

- src/Fields/index.ts
fix: export already implemented component switch field
> Export Switch Field

- src/Fields/index.stories.tsx
- src/Provider/index.stories.tsx
- src/Space/index.stories.tsx
- src/Space/index.tsx
- src/UserDetailsPopover/UserDetails.tsx
- src/UserDetailsPopover/index.stories.tsx
An often used variant of the `<Space>` is `<Space direction="vertical">`. 
This PR introduces a shorthand for it: `<VSpace>`.
> feat: add VSpace

- src/UserDetailsPopover/PhoneRow.tsx
- src/UserDetailsPopover/UserDetails.tsx
- src/UserDetailsPopover/index.stories.tsx
- src/UserDetailsPopover/phone.test.ts
- src/UserDetailsPopover/phone.ts
If a phone is available, it will be shown inside the UserDetailsPopover.
> feat: add callto link to user details

- src/ImageMap/index.stories.tsx
- src/Plate/EmptyWell.tsx
- src/Plate/FilledWell.tsx
- src/Plate/RowLabel.tsx
- src/Plate/Well.tsx
- src/Plate/constants.ts
- src/Plate/coordinateSystem96Well.ts
- src/Plate/index.stories.tsx
- src/Plate/index.test.tsx
- src/Plate/index.tsx
- src/Plate/types.ts
- src/Plate/utils.test.tsx
- src/Plate/utils.ts
BREAKING CHANGE: require explicit coordinate system value and type instead of implicit 96 well
> feat: support Plates with other coordinate systems then 96 wells

- src/ImageMap/index.stories.tsx
- src/Plate/coordinateSystem12x8.ts
- src/Plate/index.stories.tsx
- src/Plate/index.test.tsx
- src/Plate/index.tsx
- src/Plate/utils.test.tsx
BREAKING CHANGE: rename COORDINATE_SYSTEM_96_WELL,CoordinateSystem96Well
> feat: add COORDINATE_SYSTEM_12X8, CoordinateSystem12X8

- src/TreeSelect/index.stories.tsx
- src/TreeSelect/index.tsx
Currently, the `font-size` is static `12px`. This PR uses values from the theme.
> feat: theme aware TreeSelect

- src/RangeWithValue/index.stories.tsx
- src/RangeWithValue/index.tsx
> feat: add `showMean` prop to RangeWithValue component

- src/RangeWithValue/index.tsx
> fix: adjust positioning logic for mean label in RangeWithValue component
